# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Set the working directory in the container
WORKDIR /app

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . ./